# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/ue/5.3/UnrealEngine
GAMEPROJECTFILE =/mnt/ue/ue-projs/AuraProject/AuraProject.uproject

TARGETS = \
	UnrealClient-Linux-Debug  \
	UnrealClient-Linux-DebugGame  \
	UnrealClient-Linux-Test  \
	UnrealClient-Linux-Shipping  \
	UnrealClient \
	UnrealEditor-Linux-Debug  \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Test  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-Debug  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Test  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	UnrealServer-Linux-Debug  \
	UnrealServer-Linux-DebugGame  \
	UnrealServer-Linux-Test  \
	UnrealServer-Linux-Shipping  \
	UnrealServer \
	AuraProject-Linux-Debug  \
	AuraProject-Linux-DebugGame  \
	AuraProject-Linux-Test  \
	AuraProject-Linux-Shipping  \
	AuraProject \
	AuraProjectEditor-Linux-Debug  \
	AuraProjectEditor-Linux-DebugGame  \
	AuraProjectEditor-Linux-Test  \
	AuraProjectEditor-Linux-Shipping  \
	AuraProjectEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend AuraProjectEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug AuraProjectEditor-Linux-Debug


UnrealClient-Linux-Debug:
	 $(BUILD) UnrealClient Linux Debug  $(ARGS)

UnrealClient-Linux-DebugGame:
	 $(BUILD) UnrealClient Linux DebugGame  $(ARGS)

UnrealClient-Linux-Test:
	 $(BUILD) UnrealClient Linux Test  $(ARGS)

UnrealClient-Linux-Shipping:
	 $(BUILD) UnrealClient Linux Shipping  $(ARGS)

UnrealClient:
	 $(BUILD) UnrealClient Linux Development  $(ARGS)

UnrealEditor-Linux-Debug:
	 $(BUILD) UnrealEditor Linux Debug  $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Test:
	 $(BUILD) UnrealEditor Linux Test  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-Debug:
	 $(BUILD) UnrealGame Linux Debug  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Test:
	 $(BUILD) UnrealGame Linux Test  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealServer-Linux-Debug:
	 $(BUILD) UnrealServer Linux Debug  $(ARGS)

UnrealServer-Linux-DebugGame:
	 $(BUILD) UnrealServer Linux DebugGame  $(ARGS)

UnrealServer-Linux-Test:
	 $(BUILD) UnrealServer Linux Test  $(ARGS)

UnrealServer-Linux-Shipping:
	 $(BUILD) UnrealServer Linux Shipping  $(ARGS)

UnrealServer:
	 $(BUILD) UnrealServer Linux Development  $(ARGS)

AuraProject-Linux-Debug:
	 $(PROJECTBUILD) AuraProject Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

AuraProject-Linux-DebugGame:
	 $(PROJECTBUILD) AuraProject Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

AuraProject-Linux-Test:
	 $(PROJECTBUILD) AuraProject Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

AuraProject-Linux-Shipping:
	 $(PROJECTBUILD) AuraProject Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

AuraProject:
	 $(PROJECTBUILD) AuraProject Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

AuraProjectEditor-Linux-Debug:
	 $(PROJECTBUILD) AuraProjectEditor Linux Debug  -project="$(GAMEPROJECTFILE)" $(ARGS)

AuraProjectEditor-Linux-DebugGame:
	 $(PROJECTBUILD) AuraProjectEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

AuraProjectEditor-Linux-Test:
	 $(PROJECTBUILD) AuraProjectEditor Linux Test  -project="$(GAMEPROJECTFILE)" $(ARGS)

AuraProjectEditor-Linux-Shipping:
	 $(PROJECTBUILD) AuraProjectEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

AuraProjectEditor:
	 $(PROJECTBUILD) AuraProjectEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
